# Generated by Django 4.0 on 2021-12-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zakaz_name', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Maxsulot narxi kg(da)')),
                ('m_soni', models.PositiveIntegerField(verbose_name='Buyurtma miqdori (kg) da')),
                ('s_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy Narx')),
                ('m_name', models.CharField(max_length=50, verbose_name='MIjoz nomi')),
                ('m_tel', models.CharField(max_length=13, verbose_name='MIjoz telefon raqami')),
                ('m_man', models.CharField(max_length=50, verbose_name='Yetkazib berish manzili nomi')),
                ('m_agent', models.CharField(max_length=50, verbose_name='Agent nomi')),
                ('m_time', models.CharField(max_length=100, verbose_name='Buyurma vaqti')),
                ('agent_id', models.BigIntegerField(default=1, verbose_name='Telegram ID')),
                ('t_turi', models.CharField(max_length=50, verbose_name='To`lov turi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('photo', models.CharField(max_length=200, null=True, verbose_name='Rasm file_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Narx')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='Mahsulot haqida')),
                ('category_code', models.CharField(max_length=20, verbose_name='Kategoriya kodi')),
                ('category_name', models.CharField(max_length=30, verbose_name='Kategoriya nomi')),
                ('subcategory_code', models.CharField(max_length=20, verbose_name='Ost-kategoriya kodi')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Ost-kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
                ('manzil', models.CharField(max_length=50, null=True, verbose_name='Hududi')),
            ],
        ),
    ]
