# Generated by Django 4.0 on 2021-12-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='m_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Buyurma vaqti'),
        ),
    ]
