# Generated by Django 4.0 on 2021-12-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_buyurtma_m_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='m_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Buyurma vaqti'),
        ),
    ]
