# Generated by Django 3.2.9 on 2022-01-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220122_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oshxonalar',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='first_tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='second_tag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oshxona',
        ),
        migrations.DeleteModel(
            name='First_tag',
        ),
        migrations.DeleteModel(
            name='oshxonalar',
        ),
        migrations.DeleteModel(
            name='Second_tag',
        ),
    ]
