# Generated by Django 3.2.9 on 2022-01-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_second_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='second_tag',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.second_tag', verbose_name='Ikkinchi turini:'),
        ),
    ]
