# Generated by Django 4.0.1 on 2022-01-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_second_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(verbose_name='Narx'),
        ),
    ]
